### ISSUE TITLE
Unstable trigger timing every about 8 seconds in Factor mode

### ISSUE THREAD

**Issue by ukyzky** [arirusso/twigs#2]
Unstable trigger timing every about 8 seconds in Factor mode.

So I fixed in my cloned repository. It maybe commonly work correctly.
https://github.com/ukyzky/twigs/commit/e9cd907700c96cacc3a3eaf76b055112493672d5
https://github.com/ukyzky/twigs/blob/triggerextended/releases/twigs-1.0.1-triggerextended-bugfix.tar.gz

**Comment by arirusso** [comment]
@ukyzky If you would be willing to do a pull request for this, I would be interested in merging your changes (maybe with some cleanup around it)

**Comment by arirusso** [comment]
I can't personally reproduce the problem, but given no new issues with any of my other modules I'd be willing to trust the consensus.  You're not the first person to report this.

Thanks for your work and apologies for the delay in picking this up

**Comment by ukyzky** [comment]
@arirusso Thanks, I will create pull request. But it needs some more cleanup and test. So please wait patiently.

**Comment by arirusso** [comment]
@ukyzky No problem! 
Happy to help with cleanup too
Thanks again

**Comment by ukyzky** [comment]
@arirusso I create pull request: https://github.com/arirusso/twigs/pull/3
Please confirm it.

**Comment by arirusso** [comment]
👍 PR merged and included in https://github.com/arirusso/twigs/releases/tag/v1.0.2
